### ISSUE TITLE
mit license

### ISSUE THREAD

**Issue by gmelville** [c3riley/Testah#47]
I see you have a mit license, but many files have this disclaimer.

# Copyright (c) 2014-2016 Cazena, Inc., as an unpublished work.
# This notice does not imply unrestricted or public access to these
# materials which are a trade secret of Cazena, Inc. or its
# subsidiaries or affiliates (together referred to as "Cazena"), and
# which may not be copied, reproduced, used, sold or transferred to any
# third party without Cazena's prior written consent.
#
# All rights reserved.

Does the mit license apply to this entire project?

**Comment by criley-cazena** [comment]
Those headers were unintentional, will be removed.  This is an mit license open source project.

**Comment by c3riley** [comment]
corrected in 0.3.2
